/* ===== CONFIG: paste your Supabase values (anon key is public by design; security = RLS) ===== */
const SUPABASE_URL="https://YOUR-PROJECT.supabase.co",SUPABASE_ANON_KEY="YOUR-ANON-KEY";
const T={ar:{need:"أحتاج مساعدة",give:"أريد تقديم الدعم",note:"هذه المنصة ليست علاجًا نفسيًا ولا تطبيق تعارف. في الطوارئ تواصل مع خدمات الطوارئ المحلية.",gs:"المتابعة عبر Google",out:"خروج",name:"الاسم المستعار",year:"سنة الميلاد",save:"حفظ",age:"المنصة للأعمار 12–24 فقط",topic:"الموضوع",t1:"الدراسة",t2:"مشاكل اجتماعية",t3:"الثقة بالنفس",t4:"التواصل",t5:"صعوبات يومية",t6:"أريد فقط من يسمعني",desc:"ما الذي تريد التحدث عنه؟ (لا تشارك بياناتك الشخصية)",send:"إرسال",chats:"محادثاتي",reqs:"طلبات مفتوحة",claim:"قبول الطلب",rep:"إبلاغ",blk:"حظر",why:"سبب البلاغ",apply:"التقديم كمقدم دعم",mot:"لماذا تريد تقديم الدعم؟",pend:"طلبك قيد المراجعة",ad:"الإدارة",apps:"الطلبات",users:"المستخدمون",reps:"البلاغات",aud:"سجل التدقيق",ok:"قبول",no:"رفض",sus:"تعليق",act:"تفعيل",del:"حذف",ed:"تعديل الاسم",res:"تمت المعالجة",none:"لا يوجد شيء",back:"رجوع",close:"إغلاق",age18:"تقديم الدعم لمن بلغ 18 سنة فأكثر",done:"تم"},
en:{need:"I need help",give:"I want to support",note:"This platform is not therapy and not a dating app. In an emergency contact local emergency services.",gs:"Continue with Google",out:"Sign out",name:"Nickname",year:"Birth year",save:"Save",age:"For ages 12–24 only",topic:"Topic",t1:"Studying",t2:"Social problems",t3:"Confidence",t4:"Communication",t5:"Everyday difficulties",t6:"Just someone to listen",desc:"What would you like to talk about? (don't share personal data)",send:"Send",chats:"My conversations",reqs:"Open requests",claim:"Accept",rep:"Report",blk:"Block",why:"Reason",apply:"Apply as Support Provider",mot:"Why do you want to support others?",pend:"Your application is under review",ad:"Admin",apps:"Applications",users:"Users",reps:"Reports",aud:"Audit log",ok:"Approve",no:"Reject",sus:"Suspend",act:"Activate",del:"Delete",ed:"Edit name",res:"Resolve",none:"Nothing here",back:"Back",close:"Close",age18:"Providers must be 18 or older",done:"Done"},
fr:{need:"J'ai besoin d'aide",give:"Je veux apporter du soutien",note:"Cette plateforme n'est ni une thérapie ni un site de rencontre. En cas d'urgence, contactez les services d'urgence locaux.",gs:"Continuer avec Google",out:"Quitter",name:"Pseudo",year:"Année de naissance",save:"Enregistrer",age:"Réservé aux 12–24 ans",topic:"Sujet",t1:"Études",t2:"Problèmes sociaux",t3:"Confiance en soi",t4:"Communication",t5:"Difficultés du quotidien",t6:"Simplement être écouté",desc:"De quoi voulez-vous parler ? (ne partagez pas de données personnelles)",send:"Envoyer",chats:"Mes conversations",reqs:"Demandes ouvertes",claim:"Accepter",rep:"Signaler",blk:"Bloquer",why:"Motif",apply:"Devenir bénévole de soutien",mot:"Pourquoi voulez-vous soutenir ?",pend:"Votre demande est en cours d'examen",ad:"Admin",apps:"Candidatures",users:"Utilisateurs",reps:"Signalements",aud:"Journal d'audit",ok:"Approuver",no:"Refuser",sus:"Suspendre",act:"Activer",del:"Supprimer",ed:"Modifier le nom",res:"Traité",none:"Rien ici",back:"Retour",close:"Fermer",age18:"Les bénévoles doivent avoir 18 ans ou plus",done:"Fait"}};
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY),$=s=>document.getElementById(s);
Object.assign(T.ar,{h1:"مساحة آمنة للشباب لتجد من يسمعك ويدعمك",h2:"دعم محترم بين الأقران، مجاني وسري. ليست علاجًا نفسيًا.",f1:"مقدمو دعم موثّقون",g1:"كل مقدم دعم يُراجَع ويُعتمد من الإدارة.",f2:"خصوصية وأمان",g2:"محادثات خاصة، حظر وإبلاغ في كل لحظة.",f3:"ثلاث لغات",g3:"العربية والإنجليزية والفرنسية."});
Object.assign(T.en,{h1:"A safe space for young people to be heard and supported",h2:"Respectful peer support, free and private. Not therapy.",f1:"Verified supporters",g1:"Every provider is reviewed and approved by admins.",f2:"Privacy & safety",g2:"Private chats, block and report anytime.",f3:"Three languages",g3:"Arabic, English and French."});
Object.assign(T.fr,{h1:"Un espace sûr pour être écouté et soutenu",h2:"Soutien respectueux entre pairs, gratuit et privé. Pas une thérapie.",f1:"Bénévoles vérifiés",g1:"Chaque bénévole est examiné et approuvé par l'équipe.",f2:"Vie privée et sécurité",g2:"Discussions privées, blocage et signalement à tout moment.",f3:"Trois langues",g3:"Arabe, anglais et français."});
let lang=localStorage.lang||"ar",me=null,timer=null;
const t=k=>T[lang][k]||k,esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function setL(l){lang=l;localStorage.lang=l;document.documentElement.lang=l;document.title=t("h1");document.documentElement.dir=l=="ar"?"rtl":"ltr";$("lg").value=l;go()}
const view=h=>{clearInterval(timer);$("app").innerHTML=h};
async function init(){const{data:{session}}=await sb.auth.getSession();$("lg").value=lang;
 $("out").innerHTML=session?`<button onclick="sb.auth.signOut().then(()=>location.reload())">${t("out")}</button>`:"";
 if(!session)return view(`<section class="hero"><h1>${t("h1")}</h1><p>${t("h2")}</p><button class="w" onclick="sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}})">${t("gs")}</button></section><div class="feat">${[1,2,3].map(i=>`<div class="card"><b>${t("f"+i)}</b><p class="m">${t("g"+i)}</p></div>`).join("")}</div><p class="m">${t("note")}</p>`);
 const{data}=await sb.from("profiles").select("*").eq("id",session.user.id).maybeSingle();me=data||{id:session.user.id};go()}
async function go(){if(!me)return init();$("out").firstChild&&($("out").firstChild.textContent=t("out"));
 if(!me.role)return onboard();if(me.status!="active")return view(`<div class="card">⛔</div>`);if(window.ADMIN_PAGE)return me.role=="admin"?admin("apps"):view(`<div class="card">⛔ 403</div>`);home()}
function onboard(){view(`<div class="card"><p class="m">${t("age")}</p><input id="n" placeholder="${t("name")}" maxlength="30"><input id="y" type="number" placeholder="${t("year")}"><button class="p" onclick="saveP()">${t("save")}</button></div>`)}
async function saveP(){const y=+$("y").value,n=$("n").value.trim(),yr=new Date().getFullYear();if(!n||y<yr-24||y>yr-12)return alert(t("age"));
 const{error}=await sb.from("profiles").insert({id:me.id,display_name:n,birth_year:y});if(error)return alert(error.message);me=null;init()}
async function home(){let h=`<p class="m">${t("note")}</p>`;
 if(me.role=="admin")h+=`<a class="btn" href="admin/">${t("ad")} →</a>`;
 h+=`<div class="big"><button class="p" onclick="newReq()">${t("need")}</button><button onclick="give()">${t("give")}</button></div><div id="l"></div>`;view(h);chats()}
async function chats(){const{data}=await sb.from("conversations").select("*").order("id",{ascending:false});let h=`<h3>${t("chats")}</h3>`;
 (data||[]).filter(c=>c.seeker_id==me.id||c.provider_id==me.id).forEach(c=>h+=`<div class="card"><button onclick="chat(${c.id})">${esc(c.topic)} · #${c.id}</button></div>`);$("l").innerHTML=h}
function newReq(){view(`<button onclick="home()">${t("back")}</button><div class="card"><label>${t("topic")}</label><select id="tp">${[1,2,3,4,5,6].map(i=>`<option value="${i}">${t("t"+i)}</option>`).join("")}</select><textarea id="d" rows="4" placeholder="${t("desc")}" maxlength="500"></textarea><button class="p" onclick="mk()">${t("send")}</button></div>`)}
async function mk(){const tp=T[lang]["t"+$("tp").value],d=$("d").value.trim();const{data,error}=await sb.from("conversations").insert({seeker_id:me.id,topic:tp}).select().single();if(error)return alert(error.message);
 if(d)await sb.from("messages").insert({conversation_id:data.id,sender_id:me.id,body:d});chat(data.id)}
async function give(){if(me.role=="seeker"){const{data}=await sb.from("applications").select("*").eq("user_id",me.id);
  if(data&&data.length)return view(`<button onclick="home()">${t("back")}</button><div class="card">${t("pend")}: ${data[0].status}</div>`);
  return view(`<button onclick="home()">${t("back")}</button><div class="card"><p class="m">${t("age18")}</p><textarea id="mo" rows="5" placeholder="${t("mot")}"></textarea><button class="p" onclick="ap()">${t("apply")}</button></div>`)}
 const{data}=await sb.from("conversations").select("*").is("provider_id",null).eq("status","open");let h=`<button onclick="home()">${t("back")}</button><h3>${t("reqs")}</h3>`;
 (data||[]).forEach(c=>h+=`<div class="card">${esc(c.topic)} <button class="p" onclick="sb.rpc('claim_conversation',{cid:${c.id}}).then(()=>chat(${c.id}))">${t("claim")}</button></div>`);view(h+((data||[]).length?"":`<p class="m">${t("none")}</p>`))}
async function ap(){const{error}=await sb.from("applications").insert({user_id:me.id,motivation:$("mo").value.trim()});if(error)return alert(error.message);give()}
async function chat(id){const{data:c}=await sb.from("conversations").select("*").eq("id",id).single();const other=c.seeker_id==me.id?c.provider_id:c.seeker_id;
 view(`<button onclick="home()">${t("back")}</button> <button class="x" onclick="rp(${id},'${other}')">${t("rep")}</button> <button class="x" onclick="bk('${other}')">${t("blk")}</button>
 <div class="card" id="ms" style="min-height:260px;max-height:55vh;overflow:auto"></div><div class="row"><input id="b" style="flex:1" maxlength="2000"><button class="p" onclick="sd(${id})">${t("send")}</button></div>`);
 const load=async()=>{const{data}=await sb.from("messages").select("*").eq("conversation_id",id).order("id");$("ms").innerHTML=(data||[]).map(m=>`<div class="msg ${m.sender_id==me.id?"me":""}">${esc(m.body)}</div>`).join("")};await load();timer=setInterval(load,4000)}
async function sd(id){const b=$("b").value.trim();if(!b)return;const{error}=await sb.from("messages").insert({conversation_id:id,sender_id:me.id,body:b});if(error)return alert(error.message);$("b").value="";chat(id)}
async function rp(cid,u){const r=await ask(t("why"));if(!r)return;await sb.from("reports").insert({reporter_id:me.id,reported_id:u||null,conversation_id:cid,reason:r});alert(t("done"))}
async function bk(u){if(!u)return;await sb.from("blocks").upsert({blocker:me.id,blocked:u});alert(t("done"))}
async function admin(tab){const bar=["apps","users","reps","aud"].map(k=>`<button onclick="admin('${k}')">${t(k)}</button>`).join(" ");let h=`<div class="tabs"><a class="btn" href="../">${t("back")}</a> ${bar}</div>`;
 if(tab=="apps"){const{data}=await sb.from("applications").select("*").eq("status","pending");(data||[]).forEach(a=>h+=`<div class="card">${esc(a.motivation)}<div class="row"><button class="p" onclick="rv(${a.id},true)">${t("ok")}</button><button class="x" onclick="rv(${a.id},false)">${t("no")}</button></div></div>`)}
 if(tab=="users"){const{data}=await sb.from("profiles").select("*").order("created_at",{ascending:false});(data||[]).forEach(u=>h+=`<div class="card">${esc(u.display_name)} · ${u.role} · ${u.status}<div class="row"><button onclick="ed('${u.id}')">${t("ed")}</button><button onclick="st('${u.id}','${u.status=="active"?"suspended":"active"}')">${u.status=="active"?t("sus"):t("act")}</button><button class="x" onclick="st('${u.id}','deleted')">${t("del")}</button></div></div>`)}
 if(tab=="reps"){const{data}=await sb.from("reports").select("*").eq("status","open");(data||[]).forEach(r=>h+=`<div class="card">${esc(r.reason)}<div class="row">${r.conversation_id?`<button onclick="chat(${r.conversation_id})">#${r.conversation_id}</button>`:""}<button onclick="sb.rpc('admin_resolve_report',{rid:${r.id}}).then(()=>admin('reps'))">${t("res")}</button></div></div>`)}
 if(tab=="aud"){const{data}=await sb.from("audit_log").select("*").order("id",{ascending:false}).limit(100);(data||[]).forEach(l=>h+=`<div class="card m">${new Date(l.created_at).toLocaleString(lang)} · ${esc(l.action)} · ${esc(l.target)}</div>`)}
 view(h)}
const rv=(i,o)=>sb.rpc("review_application",{aid:i,ok:o}).then(()=>admin("apps"));
const st=(u,s)=>sb.rpc("admin_set_status",{uid:u,s}).then(()=>admin("users"));
const ed=async u=>{const n=await ask(t("name"));if(n)sb.rpc("admin_rename",{uid:u,n}).then(()=>admin("users"))};
setL(lang);

function ask(q){return new Promise(r=>{const d=document.createElement("dialog");d.innerHTML=`<p>${esc(q)}</p><input id="ai" maxlength="300"><div class="row"><button class="p" id="ay">${t("save")}</button><button id="an">${t("close")}</button></div>`;document.body.append(d);d.showModal();const f=v=>{d.close();d.remove();r(v)};$("ay").onclick=()=>f($("ai").value.trim());$("an").onclick=()=>f(null)})}
